### PR TITLE
implemented search artists based on country

### PR DESCRIPTION
**Pull request by bruce-wayne99**
Fixed issue #12

### CODE REVIEW

**Comment by jajodiaraghav** [comment]
Great work @bruce-wayne99 
I will wait for KWoC to officially start before merging :)

Till then, keep contributing 👍

**Comment by jajodiaraghav** [comment]
@bruce-wayne99 Can you please resolve the merge conflicts. This was introduced due to the previous PR getting merged.

**Comment by bruce-wayne99** [comment]
Resolved

**Comment by jajodiaraghav** [comment]
Awesome! Great work! Merged 🚀 

In case you are interested, I would recommend you to learn to amend and squash in git. This would greatly help in your Open Source work.
https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md

**Pull request merged**
