### PR TITLE
added the manifest file

### PR DESCRIPTION
**Pull request by hiteshpr**
Fixes [Issue #37 ](https://github.com/jajodiaraghav/rTunes/issues/37)

### CODE REVIEW

**Comment by jajodiaraghav** [comment]
favicon.png is distorted. Please replace the favicon.png file with a good quality image and rename it to icon.png

**Comment by hiteshpr** [comment]
what should be the icon? 
Can you send the icon file or we can open an issue here to create an icon file.

**Comment by jajodiaraghav** [comment]
Can we use this:

angular2

**Comment by hiteshpr** [comment]
@jajodiaraghav added the icon. Please check.

**Comment by jajodiaraghav** [comment]
Thanks @hiteshpr

**Pull request merged**
