### PR TITLE
Added environment file to store the API token

### PR DESCRIPTION
**Pull request by hiteshpr**

### CODE REVIEW

**Comment by jajodiaraghav** [comment]
@hiteshpr Thanks for the PR. This looks great!

Can you please fix the following things using git:
1. The only changes we need should be `spotify.service.ts` and `environment.ts`. You have made changes in other files which isn't required. 

2. Do you know how to squash your commits? Please squash them into one.

**Comment by jajodiaraghav** [comment]
This might help: https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md

**Comment by jajodiaraghav** [comment]
Also put package-lock.json in `.gitignore` file

**Comment by hiteshpr** [comment]
@jajodiaraghav did the changes. Please review.

**Comment by jajodiaraghav** [comment]
@hiteshpr Please read my comments. We only need about 3 file changes. I can see several other files changed.
Follow the steps:
1. Make sure you are in `environmentissue` branch
2. `git reset --soft head~4`
3. `git status` => This will show you 8 files which changed
4. `git checkout -- <filepath>` => replace filename with the filepath we get from `git status` for (Album.js, Atrist.js, package-lock.json etc)
5. `git add .`
6. `git commit`
7. `git push origin environmentissue -f`

Feel free to ask questions in case you face any issue. 
Ref: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

Remember, Proper git knowledge is a must in Software. Do not ignore it :)

**Comment by jajodiaraghav** [comment]
@hiteshpr Please tell me if you are facing any trouble.
I understand git can be challenging but trust me, without git, it is extremely difficult to contribute to FOSS.

**Comment by hiteshpr** [comment]
Hi, @jajodiaraghav I am getting this error in step 2-

> fatal: ambiguous argument 'head~4': unknown revision or path not in the working tree.

I tried many times and even searched for the solution but didn't get any. I am in `environmentissue` branch.

**Pull request closed without merging**
