### PR TITLE
service worker working workbox

### PR DESCRIPTION
**Pull request by hiteshpr**

### CODE REVIEW

**Comment by jajodiaraghav** [comment]
Looks good. 
We ca still include several other features in SW :)

Don't forget to mention: Fixes #38

**Comment by hiteshpr** [comment]
@jajodiaraghav the app is still not functioning in offline mode. Why is that? Maybe I can improve SW

**Comment by jajodiaraghav** [comment]
I think the SW file is incorrect. Please modify the file so as to make it work.

**Comment by hiteshpr** [comment]
@jajodiaraghav  You got any tutorials? Whichever I got used angular-cli and webpack .

**Pull request merged**
